version: '3.3'
services:
  soap:
    build: .
    container_name: sepotipayi-soap-service
    volumes:
      - ./:/usr/src/app
    ports:
      - 7070:7070
  mysql:
    container_name: sepotipayi-soap-db
    image: mysql:latest
    ports:
      - 3316:3306
    volumes:
      - ./sepotipayi_soap.sql:/docker-entrypoint-initdb.d/sepotipayi_soap.sql:ro
volumes:
  db:
    driver: local
